### ISSUE TITLE
Create Debian/Ubuntu repositories

### ISSUE THREAD

**Issue by dpq** [VrayoSystems/vtrunkd#206]
Create and host Debian [wheezy, jessie] and Ubuntu [LTS+modern] repos at apt.vrayo.com.

**Comment by dpq** [comment]
We've decided to use launchpad instead: https://launchpad.net/~vrayo

**Comment by grandrew** [comment]
actually, we still need:
- [ ] somewhere to store proprietary deb package for vtrunkd_helper and be able to auto-update it
- [ ] have a separate repo for customer-specific builds
- [ ] have a repo for paid updates (as redhat has)
- [ ] finally, we will need a repo clone of the official ubuntu repo for our devices as we want to prevent users for updating to unsupported system/packages versions

this may be another issue(s) though

Did you find a way to force push the repo, keys, and enable auto-update for the user when installing a deb package?

**Comment by dpq** [comment]
> Did you find a way to force push the repo, keys, and enable auto-update for the user when installing a deb package?

Repo and auto-update - yes. That's as easy as creating a debian/postinst script with something like `echo "deb [arch=amd64] http://apt.vrayo.com jessie main" > /apt/sources.list.d/vrayo.list`

Propagating the keys will take some doing, but it's relatively easy as well.

**Comment by dpq** [comment]
Since we'll have to make a private repo anyway (launchpad doesn't accept binary packages, it builds everything on site), I recommend we reverse our decision and abandon LP.

**Comment by grandrew** [comment]
moved to vrayo-service as it is irrelevant here
